import { useEffect, useState } from 'react'

import {
  FileText,
  Sparkles,
  List,
  HelpCircle,
  BriefcaseBusiness,
  Lightbulb,
  RefreshCw,
  CheckCircle2,
  AlertCircle,
  ChevronDown,
  WandSparkles,
} from 'lucide-react'

import { getDocuments } from '../services/documentService'

import {
  generateSummary,
  generateKeywords,
  generateKeyPoints,
  generateFAQs,
  generateInterviewQuestions,
  generateSuggestedQuestions,
} from '../services/aiService'

import SummaryCard from '../components/ai/SummaryCard'
import KeywordsCard from '../components/ai/KeywordsCard'
import KeyPointsCard from '../components/ai/KeyPointsCard'
import FAQCard from '../components/ai/FAQCard'
import InterviewCard from '../components/ai/InterviewCard'
import SuggestedQuestions from '../components/ai/SuggestedQuestions'

function AITools() {
  const [documents, setDocuments] = useState([])
  const [selectedDocumentId, setSelectedDocumentId] = useState('')
  const [selectedTool, setSelectedTool] = useState('summary')
  const [result, setResult] = useState(null)
  const [loadingDocuments, setLoadingDocuments] = useState(true)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  const tools = [
    {
      id: 'summary',
      title: 'Summary',
      description:
        'Generate a concise overview of the selected document.',
      icon: FileText,
      accent:
        'bg-blue-50 text-blue-600',
      selected:
        'border-blue-500 bg-blue-50/70',
    },
    {
      id: 'keywords',
      title: 'Keywords',
      description:
        'Extract the most important keywords and concepts.',
      icon: Sparkles,
      accent:
        'bg-violet-50 text-violet-600',
      selected:
        'border-violet-500 bg-violet-50/70',
    },
    {
      id: 'key-points',
      title: 'Key Points',
      description:
        'Identify the main points and important information.',
      icon: List,
      accent:
        'bg-emerald-50 text-emerald-600',
      selected:
        'border-emerald-500 bg-emerald-50/70',
    },
    {
      id: 'faqs',
      title: 'FAQs',
      description:
        'Generate frequently asked questions and answers.',
      icon: HelpCircle,
      accent:
        'bg-amber-50 text-amber-600',
      selected:
        'border-amber-500 bg-amber-50/70',
    },
    {
      id: 'interview',
      title: 'Interview Questions',
      description:
        'Generate interview questions with expected answers.',
      icon: BriefcaseBusiness,
      accent:
        'bg-rose-50 text-rose-600',
      selected:
        'border-rose-500 bg-rose-50/70',
    },
    {
      id: 'suggested',
      title: 'Suggested Questions',
      description:
        'Generate useful questions you can ask about the document.',
      icon: Lightbulb,
      accent:
        'bg-cyan-50 text-cyan-600',
      selected:
        'border-cyan-500 bg-cyan-50/70',
    },
  ]

  const getDocumentId = (
    document
  ) => {
    return (
      document?.document_id ||
      document?.id ||
      document?._id
    )
  }

  const loadDocuments =
    async () => {
      try {
        setLoadingDocuments(
          true
        )
        setError('')

        const data =
          await getDocuments()

        const documentList =
          Array.isArray(data)
            ? data
            : data?.items ||
              data?.documents ||
              []

        setDocuments(
          documentList
        )

        if (
          documentList.length > 0 &&
          !selectedDocumentId &&
          !sessionStorage.getItem('agent:ai-result')
        ) {
          setSelectedDocumentId(
            String(
              getDocumentId(
                documentList[0]
              )
            )
          )
        }
      } catch (error) {
        console.error(
          'AI Tools document loading error:',
          error
        )

        setError(
          error.response?.data
            ?.detail ||
            'Unable to load documents.'
        )
      } finally {
        setLoadingDocuments(
          false
        )
      }
    }

  useEffect(() => {
    loadDocuments()
  }, [])

  /*
   * Receive a result generated by
   * Enterprise Agent.
   *
   * sessionStorage handles the case
   * where navigation happens before
   * this page mounts.
   */
  useEffect(() => {
    const toolMap = {
      summarize_document:
        'summary',
      generate_keywords:
        'keywords',
      generate_key_points:
        'key-points',
      generate_faqs:
        'faqs',
      generate_interview_questions:
        'interview',
      suggest_questions:
        'suggested',
    }

    const toolTitles = {
      summary: 'Summary',
      keywords: 'Keywords',
      'key-points': 'Key Points',
      faqs: 'FAQs',
      interview:
        'Interview Questions',
      suggested:
        'Suggested Questions',
    }

    const applyAgentResult =
      (payload) => {
        if (!payload) {
          return
        }

        const mappedTool =
          toolMap[
            payload.tool
          ]

        if (
          payload.documentId
        ) {
          setSelectedDocumentId(
            String(
              payload.documentId
            )
          )
        }

        if (mappedTool) {
          setSelectedTool(
            mappedTool
          )
        }

        if (
          payload.result
        ) {
          setResult(
            payload.result
          )

          setError('')

          setSuccess(
            `${
              toolTitles[
                mappedTool
              ] ||
              'AI result'
            } generated successfully by Enterprise Agent.`
          )
        }
      }

    const handleAgentResult =
      (event) => {
        applyAgentResult(
          event.detail
        )
      }

    window.addEventListener(
      'agent:ai-result-ready',
      handleAgentResult
    )

    const storedResult =
      sessionStorage.getItem(
        'agent:ai-result'
      )

    if (storedResult) {
      try {
        applyAgentResult(
          JSON.parse(
            storedResult
          )
        )
      } catch (error) {
        console.error(
          'Unable to restore Agent AI result:',
          error
        )
      } finally {
        sessionStorage.removeItem(
          'agent:ai-result'
        )
      }
    }

    return () => {
      window.removeEventListener(
        'agent:ai-result-ready',
        handleAgentResult
      )
    }
  }, [])

  const handleGenerate =
    async () => {
      if (
        !selectedDocumentId
      ) {
        setError(
          'Please select a document first.'
        )
        return
      }

      try {
        setLoading(true)
        setError('')
        setSuccess('')
        setResult(null)

        let response

        switch (
          selectedTool
        ) {
          case 'summary':
            response =
              await generateSummary(
                selectedDocumentId
              )
            break

          case 'keywords':
            response =
              await generateKeywords(
                selectedDocumentId
              )
            break

          case 'key-points':
            response =
              await generateKeyPoints(
                selectedDocumentId
              )
            break

          case 'faqs':
            response =
              await generateFAQs(
                selectedDocumentId
              )
            break

          case 'interview':
            response =
              await generateInterviewQuestions(
                selectedDocumentId
              )
            break

          case 'suggested':
            response =
              await generateSuggestedQuestions(
                selectedDocumentId
              )
            break

          default:
            throw new Error(
              'Invalid AI tool selected.'
            )
        }

        setResult(
          response
        )

        setSuccess(
          `${
            tools.find(
              (tool) =>
                tool.id ===
                selectedTool
            )?.title ||
            'AI result'
          } generated successfully.`
        )
      } catch (error) {
        console.error(
          'AI generation error:',
          error
        )

        setError(
          error.response?.data
            ?.detail ||
            error.message ||
            'Unable to generate AI result.'
        )
      } finally {
        setLoading(
          false
        )
      }
    }

  const handleToolChange =
    (toolId) => {
      setSelectedTool(
        toolId
      )
      setResult(null)
      setError('')
      setSuccess('')
    }

  const selectedToolData =
    tools.find(
      (tool) =>
        tool.id ===
        selectedTool
    )

  const selectedDocument =
    documents.find(
      (document) =>
        String(
          getDocumentId(
            document
          )
        ) ===
        String(
          selectedDocumentId
        )
    )

  const selectedFilename =
    selectedDocument?.filename ||
    selectedDocument?.file_name ||
    selectedDocument?.name ||
    'Selected document'

  return (
    <div className="space-y-7 pb-8">

      {/* Page Header */}
      <section className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">

        <div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-blue-50 blur-3xl" />

        <div className="absolute -bottom-24 left-1/3 h-48 w-48 rounded-full bg-violet-50 blur-3xl" />

        <div className="relative flex flex-col gap-5 p-6 sm:p-7 lg:flex-row lg:items-center lg:justify-between">

          <div className="flex items-start gap-4">

            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-50 text-blue-600 ring-1 ring-blue-100">
              <Sparkles size={24} />
            </div>

            <div>

              <div className="flex flex-wrap items-center gap-2">

                <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
                  AI Tools
                </h1>

                <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-semibold text-blue-600">
                  <WandSparkles size={12} />
                  AI Powered
                </span>

              </div>

              <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">
                Generate summaries, insights,
                questions, and other useful
                content from your documents.
              </p>

            </div>
          </div>

          <div className="hidden items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 lg:flex">

            <Sparkles
              size={17}
              className="text-blue-600"
            />

            <div>

              <p className="text-xs font-semibold text-slate-700">
                Intelligent document analysis
              </p>

              <p className="mt-0.5 text-[11px] text-slate-400">
                Select a tool and generate insights
              </p>

            </div>
          </div>

        </div>
      </section>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3.5 text-sm text-red-700 shadow-sm">

          <AlertCircle
            size={18}
            className="mt-0.5 shrink-0"
          />

          <div>

            <p className="font-semibold">
              Something went wrong
            </p>

            <p className="mt-0.5 text-xs leading-5 text-red-600">
              {error}
            </p>

          </div>
        </div>
      )}

      {/* Success */}
      {success && (
        <div className="flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3.5 text-sm text-emerald-700 shadow-sm">

          <CheckCircle2
            size={18}
            className="mt-0.5 shrink-0"
          />

          <div>

            <p className="font-semibold">
              Generation complete
            </p>

            <p className="mt-0.5 text-xs text-emerald-600">
              {success}
            </p>

          </div>
        </div>
      )}

      {/* Document Selector */}
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">

        <div className="border-b border-slate-100 px-5 py-4 sm:px-6">

          <div className="flex items-center gap-3">

            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
              <FileText size={18} />
            </div>

            <div>

              <h2 className="text-sm font-semibold text-slate-900">
                Select a document
              </h2>

              <p className="mt-0.5 text-xs text-slate-400">
                Choose the document you want the AI
                tools to analyze.
              </p>

            </div>
          </div>
        </div>

        <div className="p-5 sm:p-6">

          <div className="relative">

            <select
              id="document"
              value={
                selectedDocumentId
              }
              onChange={(
                event
              ) => {
                setSelectedDocumentId(
                  event.target.value
                )
                setResult(null)
                setError('')
                setSuccess('')
              }}
              disabled={
                loadingDocuments ||
                loading
              }
              className="w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 pr-11 text-sm font-medium text-slate-700 outline-none transition-all duration-200 hover:border-slate-300 hover:bg-white focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100 disabled:cursor-not-allowed disabled:opacity-60"
            >

              {loadingDocuments ? (
                <option value="">
                  Loading documents...
                </option>
              ) : documents.length === 0 ? (
                <option value="">
                  No documents available
                </option>
              ) : (
                documents.map(
                  (document) => {
                    const id =
                      getDocumentId(
                        document
                      )

                    const filename =
                      document.filename ||
                      document.file_name ||
                      document.name ||
                      'Unnamed document'

                    return (
                      <option
                        key={id}
                        value={id}
                      >
                        {filename}
                      </option>
                    )
                  }
                )
              )}

            </select>

            <ChevronDown
              size={18}
              className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"
            />

          </div>

          {selectedDocument && (
            <div className="mt-3 flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2">

              <FileText
                size={14}
                className="shrink-0 text-blue-500"
              />

              <p className="min-w-0 truncate text-xs text-slate-500">

                <span className="font-medium text-slate-600">
                  Selected:
                </span>{' '}

                {selectedFilename}

              </p>

            </div>
          )}

        </div>
      </section>

      {/* AI Tool Selection */}
      <section>

        <div className="mb-4 flex items-end justify-between gap-4">

          <div>

            <h2 className="text-lg font-bold text-slate-900 sm:text-xl">
              Choose an AI tool
            </h2>

            <p className="mt-1 text-xs text-slate-500 sm:text-sm">
              Select what you want to generate from
              the selected document.
            </p>

          </div>

          <span className="hidden rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold text-slate-500 sm:inline-flex">
            {tools.length} tools available
          </span>

        </div>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">

          {tools.map(
            (tool) => {
              const Icon =
                tool.icon

              const isSelected =
                selectedTool ===
                tool.id

              return (
                <button
                  key={
                    tool.id
                  }
                  type="button"
                  onClick={() =>
                    handleToolChange(
                      tool.id
                    )
                  }
                  disabled={
                    loading
                  }
                  className={`group relative overflow-hidden rounded-2xl border p-5 text-left transition-all duration-200 ${
                    isSelected
                      ? `${tool.selected} shadow-sm`
                      : 'border-slate-200 bg-white hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md'
                  } ${
                    loading
                      ? 'cursor-not-allowed opacity-70'
                      : ''
                  }`}
                >

                  {isSelected && (
                    <span className="absolute right-4 top-4 flex h-5 w-5 items-center justify-center rounded-full bg-white shadow-sm">

                      <CheckCircle2
                        size={16}
                        className="text-blue-600"
                      />

                    </span>
                  )}

                  <div className="flex items-start gap-4">

                    <div
                      className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl transition-transform duration-200 group-hover:scale-105 ${tool.accent}`}
                    >
                      <Icon size={21} />
                    </div>

                    <div className="min-w-0 pr-5">

                      <h3
                        className={`text-sm font-semibold ${
                          isSelected
                            ? 'text-slate-900'
                            : 'text-slate-800'
                        }`}
                      >
                        {tool.title}
                      </h3>

                      <p className="mt-1.5 text-xs leading-5 text-slate-500">
                        {tool.description}
                      </p>

                    </div>
                  </div>

                </button>
              )
            }
          )}

        </div>
      </section>

      {/* Generate */}
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">

        <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">

          <div className="flex min-w-0 items-center gap-3">

            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
              <Sparkles size={18} />
            </div>

            <div className="min-w-0">

              <p className="text-sm font-semibold text-slate-800">
                Ready to generate
              </p>

              <p className="mt-0.5 truncate text-xs text-slate-500">
                {selectedDocument
                  ? `${selectedToolData?.title} for ${selectedFilename}`
                  : 'Select a document to continue'}
              </p>

            </div>
          </div>

          <button
            type="button"
            onClick={
              handleGenerate
            }
            disabled={
              loading ||
              loadingDocuments ||
              !selectedDocumentId
            }
            className="inline-flex w-full shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-sm shadow-blue-600/20 transition-all duration-200 hover:-translate-y-0.5 hover:bg-blue-700 hover:shadow-md disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 disabled:hover:shadow-sm sm:w-auto"
          >

            {loading ? (
              <>
                <RefreshCw
                  size={17}
                  className="animate-spin"
                />

                Generating...
              </>
            ) : (
              <>
                <Sparkles size={17} />

                Generate

                <span className="hidden sm:inline">
                  {` ${selectedToolData?.title}`}
                </span>
              </>
            )}

          </button>
        </div>
      </section>

      {/* Generated Result */}
      {result && (
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">

          <div className="mb-5 flex flex-col gap-3 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between">

            <div className="flex min-w-0 items-center gap-3">

              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
                <CheckCircle2 size={19} />
              </div>

              <div className="min-w-0">

                <h2 className="text-lg font-bold text-slate-900">
                  Generated Result
                </h2>

                {result.filename && (
                  <p className="mt-1 truncate text-xs text-slate-500">
                    {result.filename}
                  </p>
                )}

              </div>
            </div>

            <span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-[11px] font-semibold text-emerald-600">

              <Sparkles size={12} />

              {selectedToolData?.title}

            </span>
          </div>

          {selectedTool ===
            'summary' && (
            <SummaryCard
              summary={
                result.summary
              }
              filename={
                result.filename
              }
            />
          )}

          {selectedTool ===
            'keywords' && (
            <KeywordsCard
              keywords={
                result.keywords
              }
            />
          )}

          {selectedTool ===
            'key-points' && (
            <KeyPointsCard
              keyPoints={
                result.key_points
              }
            />
          )}

          {selectedTool ===
            'faqs' && (
            <FAQCard
              faqs={
                result.faqs
              }
            />
          )}

          {selectedTool ===
            'interview' && (
            <InterviewCard
              questions={
                result.questions
              }
            />
          )}

          {selectedTool ===
            'suggested' && (
            <SuggestedQuestions
              questions={
                result.questions
              }
            />
          )}

        </section>
      )}

      {/* Empty State */}
      {!result &&
        !loading &&
        !error && (
          <section className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center shadow-sm sm:px-10">

            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600">
              <WandSparkles size={25} />
            </div>

            <h3 className="mt-5 text-base font-bold text-slate-900">
              Ready to generate insights
            </h3>

            <p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">
              Select a document, choose an AI tool,
              and click Generate to create useful
              insights from your document.
            </p>

            <div className="mt-5 flex flex-wrap justify-center gap-2">

              {tools
                .slice(0, 4)
                .map(
                  (tool) => (
                    <span
                      key={
                        tool.id
                      }
                      className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-medium text-slate-500"
                    >
                      {tool.title}
                    </span>
                  )
                )}

              <span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-medium text-slate-500">
                + more
              </span>

            </div>
          </section>
        )}

    </div>
  )
}

export default AITools
